//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HikersParadise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CartId { get; set; }
        public string CartName { get; set; }
        public int ProductId { get; set; }
        public int MemberId { get; set; }
        public int CartStatusId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
